sequenceDiagram
    autonumber
    participant as as API Server
    participant sn as Source Node
    participant dn as Destination Node
    participant cm as CheckpointManager
    participant cri as CRIO
    as->>dn: Create clone Pod
    dn->>cm: Create checkpoint storage
    create participant d as Checkpoint Directory <br/> (per Pod)
    cm->>d: Create directory to store checkpoints for the Pod
    loop Every normal container in Pod
        opt If checkpoint does not exist
            dn->>sn: HTTP: Create checkpoint
            sn->>dn: HTTP: Retrieve checkpoint
            dn->>cm: Store checkpoint
            cm->>d: Store checkpoint in the corresponding directory
        end
        dn->>cri: RPC: CreateContainer(ctx, podSandboxID, containerConfig, podSandboxConfig)
        dn->>cri: RPC: StartContainer(ctx, containerID)
    end
