apiVersion: v1
kind: Pod
metadata:
  name: webserver-old
spec:
  containers:
    - name: app
      image: docker.io/library/nginx:alpine
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "256Mi"
    - name: sidecar
      image: docker.io/curlimages/curl:8.3.0
      command: ["/bin/sleep", "3650d"]
      resources:
        limits:
          memory: "128Mi"
